add error messages to try to pinpoint set -e issues

diff --git a/api b/api
--- a/api
+++ b/api
@@ -260,7 +260,7 @@ mouse_move() { #move mouse to absolute position $1 (format X,Y). Rather than spe
     error "mouse_move(): $vnc_pipe does not exist. Please run the daemon_start function first."
   fi
   
-  echo "mousemove $(echo "$coordinates" | tr ',' ' ')" > "$vnc_pipe"
+  echo "mousemove $(echo "$coordinates" | tr ',' ' ')" > "$vnc_pipe" || error "mouse_move(): failed to send data to vnc pipe $vnc_pipe"
   await_vnc_acknowledgement
 }
 
@@ -269,7 +269,7 @@ mouse_click() { #normal mouse click
     error "mouse_click(): $vnc_pipe does not exist. Please run the daemon_start function first."
   fi
   
-  echo "mouseclick 1" > "$vnc_pipe"
+  echo "mouseclick 1" > "$vnc_pipe" || error "mouse_click(): failed to send data to vnc pipe $vnc_pipe"
   await_vnc_acknowledgement
 }
 
@@ -278,7 +278,7 @@ mouse_right_click() { #mouse do a right-click
     error "mouse_right_click(): $vnc_pipe does not exist. Please run the daemon_start function first."
   fi
   
-  echo "mouseclick 3" > "$vnc_pipe"
+  echo "mouseclick 3" > "$vnc_pipe" || error "mouse_right_click(): failed to send data to vnc pipe $vnc_pipe"
   await_vnc_acknowledgement
 }
 
@@ -287,7 +287,7 @@ mouse_middle_click() { #mouse press the scroll wheel
     error "mouse_middle_click(): $vnc_pipe does not exist. Please run the daemon_start function first."
   fi
   
-  echo "mouseclick 2" > "$vnc_pipe"
+  echo "mouseclick 2" > "$vnc_pipe" || error "mouse_middle_click(): failed to send data to vnc pipe $vnc_pipe"
   await_vnc_acknowledgement
 }
 
